# -*- coding: utf-8 -*-
"""MADS | Oficinas Automóveis | Ambiente DEV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YrRWRKhLZqMX-Asfwxc9ZnxbPHi_HD7t

# **Gestão de Oficinas Automóveis**

Trabalho desenvolvido no ambito da unidade curricular Metodologias Ágeis de Desenvolvimento de Software.

Autores: Bernardo Pereira; Diogo Silva; Grabrielly Bresler

Explicação: Sistema de registro de compras em oficinas.

# Bibliotecas
"""

import datetime
from datetime import date, datetime as dt
import re
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import folium
from folium.plugins import MarkerCluster
import requests
import json
from IPython.display import display
import geopandas as gpd
from shapely.geometry import Point

"""# "Base de dados"
"""

utilizadores = {}
categoriasOficinas = []
oficinas = {}
compras = {}

"""# Função Adicionar Utilizador

"""

def addUser(nome: str, nif: int, dataNascimento: str, genero: str):

    erros = []

    # Verificar se todos os campos foram preenchidos
    if not all([nome, nif, dataNascimento, genero]):
        erros.append("Erro: Todos os campos são obrigatórios.")

    # Validar nome (string)
    if not isinstance(nome, str):
        erros.append("Erro: O nome deve ser texto.")
    elif not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ\s]+", nome):
        erros.append("Erro: O nome não pode conter números ou caracteres especiais.")

    # Validar NIF
    if not isinstance(nif, str):
        erros.append("Erro: O NIF deve ser texto numérico.")
    elif not nif.isdigit():
        erros.append("Erro: O NIF deve conter apenas números.")
    elif len(nif) != 9:
        erros.append("Erro: O NIF deve ter exatamente 9 dígitos.")
    elif nif in utilizadores:
        erros.append("Erro: Esse NIF já está registado!")


    # Validar data (apenas números e no formato: YYYY-MM-DD)
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", dataNascimento):
        erros.append("Erro: A data de nascimento deve conter apenas números no formato YYYY-MM-DD.")
    else:
      try:
        data_convertida = datetime.datetime.strptime(dataNascimento, "%Y-%m-%d").date()

      except ValueError:
        erros.append("Erro: Data de nascimento inválida. Use o formato YYYY-MM-DD.")

    # Verificar se é data futura
    hoje = datetime.date.today()

    if data_convertida > hoje:
        erros.append("Erro: A data de nascimento não pode ser futura.")


    # Validar género
    generos_validos = ["M", "F", "Outro"]
    if genero not in generos_validos:
        erros.append("Erro: Gênero inválido. Use 'M', 'F' ou 'Outro'.")

    # Se houver erros, mostrar todos, se não, criar utilizador
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return
      # [PCP] falta aqui um else, não ?
      # [Diogo Silva] - Não, se houver erros encontrados ele da return e não cria utilizadores.

    utilizadores[nif] = {
        "Nome": nome,
        "NIF": nif,
        "Data Nascimento": data_convertida,
        "Gênero": genero,
        "CriadoEm": datetime.datetime.now()
      }
    print(f"Utilizador registado com sucesso! NIF: {nif} ")

"""# Função Registar Categoria Oficina"""

def addCatOficina(categoria: str, cor: str):
    erros = []
    # Lista de cores permitidas para os markers
    cores_permitidas = [
        'white', 'lightgray', 'green', 'lightgreen', 'beige', 'lightblue',
        'darkblue', 'darkpurple', 'darkred', 'black', 'darkgreen', 'purple',
        'cadetblue', 'gray', 'lightred', 'red', 'pink', 'blue', 'orange'
    ]

    # Verificar se todos os campos foram preenchidos
    if not all([categoria, cor]):
        erros.append("Erro: Todos os campos são obrigatórios.")

    # Validar categoria
    if not isinstance(categoria, str):
        erros.append("A categoria deve ser texto.")
    else:
        categoria = categoria.strip()
        if not categoria:
            erros.append("A categoria não pode estar vazia.")
        if len(categoria) < 3:
            erros.append("A categoria deve ter pelo menos 3 caracteres.")
        # Validar duplicados agora acessando a chave 'nome'
        if categoria.lower() in [c['nome'].lower() for c in categoriasOficinas]:
            erros.append(f"Essa categoria - `{categoria}` - já existe. Para conhecer as categorias que já existem, faça listarCategorias().")

    # Validar cor
    if not isinstance(cor, str):
        erros.append("A cor deve ser texto.")
    else:
        cor = cor.strip().lower()
        if not cor:
            erros.append("A cor não pode estar vazia.")
        elif cor not in cores_permitidas:
            erros.append(f"A cor '{cor}' não é permitida. Escolha uma destas: {', '.join(cores_permitidas)}")
        elif cor in [c['cor'] for c in categoriasOficinas]:
            erros.append(f"A cor '{cor}' já foi usada em outra categoria. Escolha uma cor diferente.")

    # Mostrar erros
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

    # Adicionar categoria como dicionário
    categoriasOficinas.append({"nome": categoria, "cor": cor})
    print(f"Categoria '{categoria}' adicionada com sucesso! Cor: {cor}")

"""# Função Registar Oficinas"""

def addOficina(nif: str, nome: str, categoria: str, latitude: float, longitude: float,
               morada: str, cidade: str, codigoPostal: str, horario: str):

    erros = []

    # Verificar se todos os campos foram preenchidos
    if not all([nif, nome, categoria, latitude, longitude, morada, cidade, codigoPostal, horario]):
        erros.append("Erro: Todos os campos são obrigatórios.")

    # Validar NIF
    if not isinstance(nif, str):
        erros.append("Erro: O NIF deve ser texto numérico.")
    elif not nif.isdigit():
        erros.append("Erro: O NIF deve conter apenas números.")
    elif len(nif) != 9:
        erros.append("Erro: O NIF deve ter exatamente 9 dígitos.")
    elif nif in oficinas:
        erros.append("Erro: Já existe uma oficina registada com esse NIF.")

    # Validar nome
    if not isinstance(nome, str):
        erros.append("Erro: O nome da oficina deve ser texto.")
    else:
        nome = nome.strip()
        if not nome:
            erros.append("Erro: O nome da oficina não pode estar vazio.")

    # Validar categoria
    if not isinstance(categoria, str):
        erros.append("Erro: A categoria deve ser texto.")
    elif categoria not in [c["nome"] for c in categoriasOficinas]:
        erros.append("Erro: Categoria inválida. Use listarCategorias() para ver as disponíveis.")

    # Validar categoria
    if not isinstance(categoria, str):
        erros.append("Erro: A categoria deve ser texto.")
    elif categoria not in [c["nome"] for c in categoriasOficinas]:
        erros.append("Erro: Categoria inválida. Use listarCategorias() para ver as disponíveis.")

    # Validar latitude/longitude
    if latitude < -90 or latitude > 90:
      erros.append("Erro: Latitude deve estar entre -90 e 90.")

    if longitude < -180 or longitude > 180:
      erros.append("Erro: Longitude deve estar entre -180 e 180.")

    #if (-90 <= latitude <= 90) and (-180 <= longitude <= 180):
        #if not ponto_dentro_maia(latitude, longitude):
          #erros.append("Erro: As coordenadas fornecidas não estão dentro dos limites da Maia.")



    # Validar morada
    if not isinstance(morada, str):
        erros.append("Erro: A morada deve ser texto.")
    else:
        morada = morada.strip()
        if not morada:
            erros.append("Erro: A morada não pode estar vazia.")

    # Validar cidade
    if not isinstance(cidade, str):
        erros.append("Erro: A cidade deve ser texto.")
    else:
        cidade = cidade.strip()
        if not cidade:
            erros.append("Erro: A cidade não pode estar vazia.")

    # Validar código postal
    if not isinstance(codigoPostal, str):
        erros.append("Erro: O código postal deve ser texto.")
    elif len(codigoPostal) != 8 or codigoPostal[4] != "-":
        erros.append("Erro: O código postal deve ter o formato XXXX-XXX.")

    # Validar horário
    if not isinstance(horario, str):
        erros.append("Erro: O horário deve ser texto.")
    else:
        horario = horario.strip()
        if not horario:
            erros.append("Erro: O horário não pode estar vazio.")

    # Mostrar erros
    if erros:
        print("Foram encontrados erros no comando:")
        for erro in erros:
            print(f"- {erro}")
        return

    # Registar oficina
    oficinas[nif] = {
        "NIF": nif,
        "Nome": nome,
        "Categoria": categoria,
        "Latitude": latitude,
        "Longitude": longitude,
        "Morada": morada,
        "Cidade": cidade,
        "CodigoPostal": codigoPostal,
        "Horario": horario,
        "CriadoEm": datetime.datetime.now()
    }

    print(f"Oficina registada com sucesso! NIF: {nif}")

"""# Função Registar Compra

"""

def registarCompra(nifUtilizador: str, nifOficina: str, valor: float, descricao: str, dataCompra: str, catCompra: str):

    erros = []

    # Verificar se todos os campos foram preenchidos
    if not all([nifUtilizador, nifOficina, valor, descricao]):
        erros.append("Erro: Todos os campos são obrigatórios.")

    # Validar NIF do utilizador
    if not isinstance(nifUtilizador, str):
        erros.append("Erro: O NIF do utilizador deve ser texto numérico.")
    elif not nifUtilizador.isdigit():
        erros.append("Erro: O NIF do utilizador deve conter apenas números.")
    elif len(nifUtilizador) != 9:
        erros.append("Erro: O NIF do utilizador deve ter 9 dígitos.")
    elif nifUtilizador not in utilizadores:
        erros.append("Erro: Não existe nenhum utilizador com esse NIF.")

    # Validar NIF da oficina
    if not isinstance(nifOficina, str):
        erros.append("Erro: O NIF da oficina deve ser texto numérico.")
    elif not nifOficina.isdigit():
        erros.append("Erro: O NIF da oficina deve conter apenas números.")
    elif len(nifOficina) != 9:
        erros.append("Erro: O NIF da oficina deve ter 9 dígitos.")
    elif nifOficina not in oficinas:
        erros.append("Erro: Não existe nenhuma oficina com esse NIF.")

    # Validar valor
    if not isinstance(valor, (int, float)):
        erros.append("Erro: O valor da compra deve ser numérico.")
    elif valor <= 0:
        erros.append("Erro: O valor da compra deve ser maior que zero.")

    # Validar descrição
    if not isinstance(descricao, str):
        erros.append("Erro: A descrição deve ser texto.")
    else:
        descricao = descricao.strip()
        if not descricao:
            erros.append("Erro: A descrição não pode estar vazia.")
        elif len(descricao) < 3:
            erros.append("Erro: A descrição deve ter pelo menos 3 caracteres.")

    # Validar data (apenas números e no formato: YYYY-MM-DD)
    data_convertida = None

    if not isinstance(dataCompra, str) or not re.match(r"^\d{4}-\d{2}-\d{2}$", dataCompra):
        erros.append("Erro: A data de compra deve estar no formato YYYY-MM-DD.")
    else:
        try:
            data_convertida = datetime.datetime.strptime(dataCompra, "%Y-%m-%d").date()
        except ValueError:
            erros.append("Erro: Data de compra inválida.")

    # Verificar se é futura
    if data_convertida:
        hoje = datetime.date.today()
        if data_convertida > hoje:
            erros.append("Erro: A data de compra não pode ser futura.")

    # Validar categoria de compra
    categoria_compra = ["P", "S"]
    if catCompra not in categoria_compra:
        erros.append("Erro: Categoria de compra inválido. Use 'P' para 'Produto' ou 'S' para 'Serviço'.")

    # Verificar se a compra já existe (todos os dados iguais)
    for compra in compras.values():
        if (compra["NIF_Utilizador"] == nifUtilizador and
            compra["NIF_Oficina"] == nifOficina and
            compra["Valor"] == valor and
            compra["Descricao"] == descricao and
            compra["Categoria_Compra"] == catCompra):
            erros.append("Erro: Já existe uma compra registada com os mesmos dados.")
            break

    # Mostrar erros
    if erros:
        print("Foram encontrados erros no comando:")
        for erro in erros:
            print(f"- {erro}")
        return

    # Criar ID da compra
    idCompra = len(compras) + 1

    # Registar compra
    compras[idCompra] = {
        "ID": idCompra,
        "NIF_Utilizador": nifUtilizador,
        "NIF_Oficina": nifOficina,
        "Valor": valor,
        "Descricao": descricao,
        "Data": data_convertida,
        "Categoria_Compra": catCompra,
    }

    print(f"Compra registada com sucesso! ID da compra: {idCompra}")

"""# Listar Categorias de Oficinas"""

def listarCategorias():
    if not categoriasOficinas:
        print("Nenhuma categoria cadastrada.")
        return

    # Cria DataFrame com todos os campos
    df = pd.DataFrame([{"Nome": c["nome"], "Cor": c["cor"]} for c in categoriasOficinas])

    # Cria estilo: células centralizadas
    styled_df = (df.style.set_properties(**{'text-align': 'center'}).set_table_styles([{'selector': 'th', 'props': [('text-align', 'center')]}]))

    display(styled_df)

"""# Listar Oficinas

Sem filtro - (listarOficinas())

Com filtro - 'exemplo': (listarOficinas(categoria = "Mecânica"))
"""

def listarOficinas(nif = None, nome = None, categoria = None, cidade = None):
    if not oficinas:
        print("Nenhuma Oficina Registada.")
        return

    # Cria DataFrame com todos os campos
    df = pd.DataFrame([oficina for oficina in oficinas.values()])

    # Aplica filtros
    if nif:
        df = df[df["NIF"] == nif]

    if nome:
        df = df[df["Nome"].str.contains(nome, case=False)]

    if categoria:
        df = df[df["Categoria"] == categoria]

    if cidade:
        df = df[df["Cidade"].str.contains(cidade, case=False)]

    if df.empty:
        print("Nenhuma oficina encontrada com esses filtros.")
        return

    # Reordena colunas
    colunas = ["NIF", "Nome", "Categoria", "Latitude", "Longitude",
               "Morada", "Cidade", "CodigoPostal", "Horario", "CriadoEm"]
    df = df[colunas]

    # Cria estilo: células centralizadas
    styled_df = (df.style.set_properties(**{'text-align': 'center'}).set_table_styles([{'selector': 'th','props': [('text-align', 'center')]}]))

    display(styled_df)

"""# Listar Utilizadores

Sem filtro - (listarUtilizador())

Com filtro - 'exemplo': (listarUtilizador(nif = "123456789"))
"""

def listarUtilizador(nif = None, nome = None, genero = None):
    if not utilizadores:
        print("Nenhum Utilizador Registrado.")
        return

    # Cria DataFrame a partir do dicionário de utilizadores
    df = pd.DataFrame([{"NIF": nif, **dados} for nif, dados in utilizadores.items()])

    # Aplica filtros
    if nif:
        df = df[df["NIF"] == nif]

    if nome:
        df = df[df["Nome"].str.contains(nome, case=False)]

    if genero:
        df = df[df["Gênero"] == genero]

    if df.empty:
        print("Nenhum utilizador encontrado com esses filtros.")
        return

    # Cria estilo: células centralizadas
    styled_df = (df.style.set_properties(**{'text-align': 'center'}).set_table_styles([{'selector': 'th', 'props': [('text-align', 'center')]}]))

    display(styled_df)

"""# Listar Compras

Sem filtro - (listarCompras())

Com filtro - 'exemplo': (listarCompras(nifUtilizador = "123456789"))

Caso Especial - (listarCompras(valorMin=50, valorMax=200))
"""

def listarCompras(idCompra = None, nifUtilizador = None, nifOficina = None, categoria = None, valorMin = None, valorMax = None, dataInicio = None, dataFim = None):
    if not compras:
        print("Nenhuma Compra Registada.")
        return

    # Cria DataFrame a partir do dicionário de compras
    df = pd.DataFrame([compra for compra in compras.values()])

    df["Data"] = pd.to_datetime(df["Data"])

    # Aplica filtros
    if idCompra:
        df = df[df["ID"] == idCompra]

    if nifUtilizador:
        df = df[df["NIF_Utilizador"] == nifUtilizador]

    if nifOficina:
        df = df[df["NIF_Oficina"] == nifOficina]

    if categoria:
        df = df[df["Categoria_Compra"] == categoria]

    if valorMin is not None:
        df = df[df["Valor"] >= valorMin]

    if valorMax is not None:
        df = df[df["Valor"] <= valorMax]

    if dataInicio:
        data_inicio = pd.to_datetime(dataInicio)
        df = df[df["Data"] >= data_inicio]

    if dataFim:
        data_fim = pd.to_datetime(dataFim)
        df = df[df["Data"] <= data_fim]

    if df.empty:
        print("Nenhuma compra encontrada com esses filtros.")
        return

    # Reordena colunas
    colunas = ["ID", "NIF_Utilizador", "NIF_Oficina", "Valor", "Descricao", "Categoria_Compra", "Data"]

    df = df[colunas]

    # Cria estilo: células centralizadas
    styled_df = (df.style.set_properties(**{'text-align': 'center'}).set_table_styles([{'selector': 'th', 'props': [('text-align', 'center')]}]))

    display(styled_df)

"""# Criar Mapa"""

from branca.element import Element

ponto=[]

def set_ponto(nome, categoria, lon, lat, cor):
  ponto.append({'nome':nome, 'categoria':categoria, 'lat':lat, 'lon':lon, 'cor':cor})
  return(ponto)

def del_ponto(nome):
  # ....
  status='to be defined'
  return(status)

def lista_pontos():
  kp=1
  for p in ponto:
    print(f"{kp:4d} {p['nome']:50s} {p['categoria']:20s} ({p['lat']:.6f}, {p['lon']:.6f})")
    kp+=1
  return

def get_gjson():
  gjson={
  "type": "FeatureCollection",
  "features": []}

  for p in ponto:
    gjson['features'].append( {
      "type": "Feature",
      "properties": { "popupContent":f"<div width:400px>{p['nome']}</div>"},
      "geometry": {
        "coordinates": [
          p['lon'],
          p['lat']
        ],
        "type": "Point"
      } }
     )

  return(gjson)

def getCorOficina(oficina_nif: str):
    if oficina_nif not in oficinas:
        return "black"  # NIF não encontrado

    categoria = oficinas[oficina_nif]["Categoria"]

    # Procurar cor na lista de categorias
    for c in categoriasOficinas:
        if c["nome"].lower() == categoria.lower():
            return c["cor"]

    return "black"  # Caso a categoria não esteja na lista


def mapa():
  # limpa possiveis pontos existentes
    ponto.clear()

  # carrega os pontos das oficinas
    for i in oficinas:
      set_ponto(
        oficinas[i]["Nome"],
        oficinas[i]["Categoria"],
        oficinas[i]["Longitude"],
        oficinas[i]["Latitude"],
        getCorOficina(oficinas[i]["NIF"])
      )

    # Limpa o mapa anterior (se necessário)

    # Carregar limites do Concelho da Maia
    aline = requests.get('http://baze.cm-maia.pt/BaZe/api/api4gj.php?nome=LimConcVM')
    aline = aline.text[1:]
    agj = json.loads(aline)

    # Create the map at Maia
    m = folium.Map(location=[41.22, -8.5795], zoom_start=12, width=1200,   height=700)  # height in pixels)

    folium.TileLayer('openstreetmap', name='OpenStreetMap').add_to(m)
    folium.TileLayer('cartodbpositron', name='CartoDB Positron').add_to(m)
    folium.TileLayer('cartodbdark_matter', name='CartoDB Dark').add_to(m)
    folium.TileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
                    name='OpenTopoMap',
                    attr='Map data: © OpenStreetMap contributors').add_to(m)
    folium.TileLayer(
        tiles='https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
        attr='Google',
        name='Google Satellite'
    ).add_to(m)

    # Add Google Terrain
    folium.TileLayer(
        tiles='https://mt1.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',
        attr='Google',
        name='Google Terrain'
    ).add_to(m)

    folium.GeoJson(
        agj,
        name='Limite do Concelho'
    ).add_to(m)

    # Adicionar limite do concelho
    folium.GeoJson(agj, name='Limite do Concelho').add_to(m)

    # Adicionar controles de camadas
    folium.LayerControl().add_to(m)

    # --- Criar legenda no canto inferior esquerdo ---
    legenda_html = """
    <div style="
        position: fixed;
        top: 10vh;
        left: 1vh;
        width: 180px;
        z-index:9999;
        font-size:14px;
        background-color:white;
        border:2px solid grey;
        padding: 10px;
        ">
        <b>Legenda de Categorias</b><br>
    """
    for c in categoriasOficinas:
        cor = c["cor"]
        nome = c["nome"]
        legenda_html += f"<i style='background:{cor}; width:15px; height:15px; display:inline-block; margin-right:5px;'></i> {nome}<br>"
    legenda_html += "</div>"

    # Adicionar a legenda ao mapa
    legenda = Element(legenda_html)
    m.get_root().html.add_child(legenda)




    # Adicionar markers com cores
    for p in ponto:
        folium.Marker(
            location=[p["lat"], p["lon"]],
            popup=p["nome"],
            icon=folium.Icon(color=p["cor"])
        ).add_to(m)

    # Salvar mapa
    m.save("mapa.html")

    # Mostrar mapa
    display(m)

"""# Estatisticas"""

def verTotalOficinas():
    total = len(oficinas)
    print(f"Número total de oficinas registadas: {total}")


def verTotalUtilizadores():
    total = len(utilizadores)
    print(f"Número total de utilizadores registados: {total}")


def consultarVolumeFaturação(nif=None):
    if not compras:
        print("Nenhuma compra registada.")
        return 0

    df = pd.DataFrame(compras.values())

    if nif:
        df = df[df["NIF_Oficina"] == nif]

    total_faturacao = df["Valor"].sum()
    if nif:
        print(f"Volume de faturação da oficina {nif}: {total_faturacao:.2f}")
    else:
        print(f"Volume total de faturação de todas as oficinas: {total_faturacao:.2f}")



def consultarMaisAdquirido(top=5):
    if not compras:
        print("Nenhuma compra registada.")
        return

    df = pd.DataFrame(compras.values())
    mais_adquiridos = df.groupby("Descricao")["Valor"].count().sort_values(ascending=False).head(top)

    print(f"Top {top} produtos/serviços mais adquiridos:")
    display(mais_adquiridos.reset_index().rename(columns={"Descricao": "Produto/Serviço", "Valor": "Quantidade"}))




def listasVolumeVendas(top=10):
    if not compras:
        print("Nenhuma compra registada.")
        return

    df = pd.DataFrame(compras.values())

    # Agrupar por NIF da oficina
    resumo = df.groupby("NIF_Oficina").agg(
        Volume_Vendas=pd.NamedAgg(column="Valor", aggfunc="sum"),
        Qtde_Compras=pd.NamedAgg(column="ID", aggfunc="count")
    ).reset_index()

    # Arredondar volume de vendas para 2 casas decimais
    resumo["Volume_Vendas"] = resumo["Volume_Vendas"].round(2)

    # Adicionar nome da oficina
    resumo["Nome_Oficina"] = resumo["NIF_Oficina"].apply(lambda x: oficinas[x]["Nome"] if x in oficinas else "Desconhecido")

    # Ordenar pelo volume de vendas
    resumo = resumo.sort_values(by="Volume_Vendas", ascending=False).head(top)

    # Mostrar tabela organizada
    resumo = resumo[["NIF_Oficina", "Nome_Oficina", "Volume_Vendas", "Qtde_Compras"]]
    print(f"Top {top} oficinas por volume de vendas:")
    display(resumo.style.set_properties(**{'text-align': 'center'}).set_table_styles([{'selector': 'th','props': [('text-align', 'center')]}]))




def visualizarEvolucaoDespesas(nifUtilizador=None):
    if not compras:
        print("Nenhuma compra registada.")
        return

    df = pd.DataFrame(compras.values())
    df["Data"] = pd.to_datetime(df["Data"])

    if nifUtilizador:
        df = df[df["NIF_Utilizador"] == nifUtilizador]

    if df.empty:
        print("Nenhuma compra encontrada para os filtros fornecidos.")
        return

    # Agrupa por data e soma valores
    df_grouped = df.groupby("Data")["Valor"].sum().reset_index()

    # Plot
    plt.figure(figsize=(10,5))
    plt.plot(df_grouped["Data"], df_grouped["Valor"], marker='o', linestyle='-')
    plt.title(f"Evolução das Despesas{' do Utilizador '+nifUtilizador if nifUtilizador else ''}")
    plt.xlabel("Data")
    plt.ylabel("Valor (€)")
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""# Exportar"""

def exportarParaJSON():
    # Função auxiliar para converter datas em strings
    def converter(obj):
        if isinstance(obj, (date, dt)):
            return obj.isoformat()  # formato 'YYYY-MM-DD' ou 'YYYY-MM-DDTHH:MM:SS'
        return obj

    # Criar dicionário principal
    dados = {
        "utilizadores": utilizadores,
        "oficinas": oficinas,
        "compras": compras,
        "categoriasOficinas": categoriasOficinas
    }

    # Exportar para ficheiro JSON com tratamento de datas
    with open("dados_exportados.json", "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=4, default=converter)

    print("Dados exportados com sucesso para 'dados_exportados.json'.")


def exportarParaCSV():
    # Exportar utilizadores
    if utilizadores:
        df_utilizadores = pd.DataFrame([{"NIF": nif, **dados} for nif, dados in utilizadores.items()])
        df_utilizadores.to_csv("utilizadores.csv", index=False, encoding="utf-8")
        print("Utilizadores exportados para 'utilizadores.csv'.")
    else:
        print("Nenhum utilizador para exportar.")

    # Exportar oficinas
    if oficinas:
        df_oficinas = pd.DataFrame(list(oficinas.values()))
        df_oficinas.to_csv("oficinas.csv", index=False, encoding="utf-8")
        print("Oficinas exportadas para 'oficinas.csv'.")
    else:
        print("Nenhuma oficina para exportar.")

    # Exportar compras
    if compras:
        df_compras = pd.DataFrame(list(compras.values()))
        df_compras.to_csv("compras.csv", index=False, encoding="utf-8")
        print("Compras exportadas para 'compras.csv'.")
    else:
        print("Nenhuma compra para exportar.")

    # Exportar categorias de oficinas
    if categoriasOficinas:
        df_categorias = pd.DataFrame(categoriasOficinas)
        df_categorias.to_csv("categoriasOficinas.csv", index=False, encoding="utf-8")
        print("Categorias de oficinas exportadas para 'categoriasOficinas.csv'.")
    else:
        print("Nenhuma categoria de oficina para exportar.")
